[package]
name = "ledecky"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bytes = "1"
flate2 = "1.1.10"
include_dir = "0.7.4"
minijinja = { version = "2", features = ["loader", "urlencode"] }
notify = "8.2.0"
pty-process = { version = "0.5", features = ["async"] }
rand = { version = "0.10", default-features = false, features = ["sys_rng"] }
rocket = { version = "0.5", features = ["json"] }
rocket_ws = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1", features = ["sync", "process", "io-util", "time", "rt", "macros"], default-features = false }
vt100 = "0.16"
